# Generated by Django 3.1.7 on 2021-04-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20210329_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_birthday',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gender',
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='client',
            name='commercial_business',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.IntegerField(blank=True, max_length=150, null=True, verbose_name='Telefono'),
        ),
    ]
