# Generated by Django 3.1.7 on 2021-04-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20210412_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='commercial_business',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Giro Comercial'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='client',
            name='names',
            field=models.CharField(max_length=150, verbose_name='Empresa'),
        ),
    ]
