# Generated by Django 3.1.7 on 2021-04-15 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.category', verbose_name='Categoría'),
        ),
    ]
