# Generated by Django 3.1.7 on 2021-04-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20210415_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detsale',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=9),
        ),
    ]
