# Generated by Django 3.1.7 on 2021-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_auto_20210420_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Email'),
        ),
    ]
