# Generated by Django 3.1.7 on 2021-07-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_auto_20210728_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dni',
            field=models.CharField(default=2, max_length=12, unique=True, verbose_name='RUT'),
            preserve_default=False,
        ),
    ]
