# Generated by Django 3.1.7 on 2021-07-28 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_client_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de Rut Incorrecto.', regex='^(\\d{1,3}(?:\\.\\d{1,3}){2}-[\\dkK])$')], verbose_name='RUT'),
        ),
    ]
