# Generated by Django 3.1.7 on 2021-07-28 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_auto_20210728_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de Rut Incorrecto.', regex='^0*(\\d{1,3}(\\.?\\d{3})*)\\-?([\\dkK])$')], verbose_name='RUT'),
        ),
    ]
