# Generated by Django 3.0.5 on 2021-08-04 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_auto_20210804_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Empresa Proveedora')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='proveedor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='erp.Proveedor', verbose_name='Empresa Proveedora'),
            preserve_default=False,
        ),
    ]
