# Generated by Django 3.0.5 on 2021-08-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0035_proveedor_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
