# Generated by Django 3.0.5 on 2021-08-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0037_proveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
