# Generated by Django 3.0.5 on 2021-08-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0043_auto_20210808_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['id'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.CharField(default=52, max_length=150, verbose_name='Compañía'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Marca'),
        ),
    ]
