# Generated by Django 3.0.5 on 2021-08-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0045_brand_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='phone',
            new_name='phone_brand',
        ),
    ]
