# Generated by Django 3.0.5 on 2021-08-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0046_auto_20210808_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
