# Generated by Django 3.0.5 on 2021-08-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0047_auto_20210808_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
