# Generated by Django 3.0.5 on 2021-08-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0050_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre Marca'),
        ),
    ]
