# Generated by Django 3.0.5 on 2021-08-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0052_brand_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='desc',
            new_name='desc_brand',
        ),
    ]
