# Generated by Django 3.0.5 on 2021-08-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0053_auto_20210808_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='desc_brand',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción Marca'),
        ),
    ]
