# Generated by Django 3.0.5 on 2021-08-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0054_auto_20210808_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='desc_brand',
            new_name='desc',
        ),
    ]
