# Generated by Django 3.0.5 on 2021-08-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0055_auto_20210808_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.PROTECT, to='erp.Brand', verbose_name='Marca'),
            preserve_default=False,
        ),
    ]
