# Generated by Django 3.0.5 on 2021-08-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0056_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='name_brand',
        ),
    ]
