# Generated by Django 3.0.5 on 2021-08-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0057_auto_20210808_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name_brand',
            new_name='name',
        ),
    ]
