# Generated by Django 3.1.7 on 2021-08-15 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0058_auto_20210808_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='names',
        ),
    ]
