# Generated by Django 3.1.7 on 2021-08-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0059_auto_20210814_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='names',
            new_name='Namespace',
        ),
    ]
