# Generated by Django 3.1.7 on 2021-08-15 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0060_auto_20210814_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='Namespace',
            new_name='names',
        ),
    ]
