# Generated by Django 3.1.7 on 2021-08-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0064_auto_20210820_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='nombremarca',
            new_name='nombre',
        ),
    ]
