# Generated by Django 3.1.7 on 2021-08-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0065_auto_20210820_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nombremarca',
            new_name='marca',
        ),
    ]
