# Generated by Django 3.1.7 on 2021-08-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0066_auto_20210820_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='detsale',
            name='formapago',
            field=models.ForeignKey(default=65, on_delete=django.db.models.deletion.CASCADE, to='erp.formaspago'),
            preserve_default=False,
        ),
    ]
