# Generated by Django 3.1.7 on 2021-08-20 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0071_formapagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='detsale',
            name='formapago',
            field=models.ForeignKey(default=72, on_delete=django.db.models.deletion.CASCADE, to='erp.formapagos'),
            preserve_default=False,
        ),
    ]
