# Generated by Django 3.1.7 on 2021-08-20 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0072_detsale_formapago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detsale',
            name='formapago',
        ),
        migrations.AddField(
            model_name='sale',
            name='formapago',
            field=models.ForeignKey(default=73, on_delete=django.db.models.deletion.CASCADE, to='erp.formapagos'),
            preserve_default=False,
        ),
    ]
