# Generated by Django 3.1.7 on 2021-08-21 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0075_auto_20210820_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='formapago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.formapagos'),
        ),
    ]
