# Generated by Django 3.1.7 on 2021-08-21 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0084_sale_formapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='formapago',
            field=models.ForeignKey(default=84, on_delete=django.db.models.deletion.PROTECT, to='erp.formapagos'),
            preserve_default=False,
        ),
    ]
