# Generated by Django 3.1.7 on 2021-08-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0086_permission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='Permissions',
        ),
    ]
