# Generated by Django 3.1.7 on 2021-08-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0087_auto_20210823_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
