# Generated by Django 3.1.7 on 2021-08-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0089_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
    ]
