# Generated by Django 3.1.7 on 2021-08-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0092_remove_client_total_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='names',
            field=models.CharField(max_length=150, unique=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Empresa Proveedora'),
        ),
    ]
