# Generated by Django 3.1.7 on 2021-08-25 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0093_auto_20210825_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.category')),
            ],
        ),
    ]
