# Generated by Django 3.1.7 on 2021-08-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0094_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='cat',
        ),
    ]
