# Generated by Django 3.1.7 on 2021-08-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0097_auto_20210825_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='namesubcat',
        ),
    ]
