# Generated by Django 3.1.7 on 2021-08-26 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0099_auto_20210825_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='namesubcat',
            new_name='subcat',
        ),
    ]
