# Generated by Django 3.1.7 on 2021-08-26 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0101_auto_20210826_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcat',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.subcategory', verbose_name='Subcategoría'),
        ),
    ]
