# Generated by Django 3.1.7 on 2021-08-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0102_auto_20210826_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='namesub',
        ),
    ]
