# Generated by Django 3.1.7 on 2021-08-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0103_auto_20210826_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcat',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
