# Generated by Django 3.1.7 on 2021-08-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0105_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcat',
            field=models.ForeignKey(default=105, on_delete=django.db.models.deletion.PROTECT, to='erp.sub', verbose_name='Subcategoría'),
            preserve_default=False,
        ),
    ]
