# Generated by Django 3.1.7 on 2021-08-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0107_remove_product_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(default=107, on_delete=django.db.models.deletion.PROTECT, to='erp.category', verbose_name='Categoría'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.sub', verbose_name='Categoría - Subcategoría'),
        ),
    ]
