# Generated by Django 3.1.7 on 2021-08-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0108_auto_20210826_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
    ]
