# Generated by Django 3.1.7 on 2021-08-31 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0113_remove_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcat',
        ),
        migrations.AlterField(
            model_name='sub',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.category', verbose_name='Subcategoría'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Subcategoría'),
        ),
    ]
