# Generated by Django 3.1.7 on 2021-10-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0114_auto_20210831_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='formapago',
        ),
        migrations.DeleteModel(
            name='FormaPagos',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
    ]
