# Generated by Django 3.1.7 on 2021-11-08 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0119_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcat',
            field=models.ForeignKey(default=118, on_delete=django.db.models.deletion.PROTECT, to='erp.subcategory', verbose_name='Subcategoría'),
            preserve_default=False,
        ),
    ]
