# Generated by Django 3.1.7 on 2021-11-08 20:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0120_product_subcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, unique=True, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de Rut Incorrecto.', regex='^0*(\\d{1,3}(\\.?\\d{3})*)\\-?([\\dkK])$')], verbose_name='RUT')),
                ('phone', models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="El número de telefono debe tener el siguiente: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ciudad')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True, verbose_name='Email')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.cargos', verbose_name='Cargo')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.department', verbose_name='Departamento')),
            ],
        ),
    ]
