# Generated by Django 3.1.7 on 2021-11-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0121_trabajador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'ordering': ['id'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
