# Generated by Django 3.1.7 on 2021-11-24 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0125_detbuy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcat',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
