# Generated by Django 3.1.7 on 2021-11-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0127_auto_20211125_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.sale', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.client', verbose_name='Cliente'),
        ),
    ]
