# Generated by Django 3.1.7 on 2021-11-27 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0128_auto_20211126_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buy',
            new_name='Compra',
        ),
        migrations.RenameModel(
            old_name='DetBuy',
            new_name='DetCompra',
        ),
    ]
