# Generated by Django 3.1.7 on 2021-11-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0129_auto_20211126_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detcompra',
            old_name='buy',
            new_name='compra',
        ),
    ]
