# Generated by Django 3.1.7 on 2021-11-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0130_auto_20211126_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='proveedor',
            new_name='prov',
        ),
    ]
