# Generated by Django 3.1.7 on 2021-11-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0131_auto_20211127_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='name',
            new_name='names',
        ),
    ]
