# Generated by Django 3.1.7 on 2021-11-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0132_auto_20211127_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='prov',
            new_name='cli',
        ),
    ]
