# Generated by Django 3.1.7 on 2021-11-27 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0133_auto_20211127_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detcompra',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='detcompra',
            name='prod',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='names',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='detsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.sale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.client'),
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='DetCompra',
        ),
    ]
