# Generated by Django 3.1.7 on 2021-11-27 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0135_auto_20211127_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='prove',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.proveedor'),
        ),
    ]
