# Generated by Django 3.1.7 on 2021-11-27 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0136_auto_20211127_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='name_prov',
            new_name='name',
        ),
    ]
