# Generated by Django 3.1.7 on 2021-11-28 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0138_auto_20211127_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detcompra',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='detcompra',
            name='prod',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='DetCompra',
        ),
    ]
