# Generated by Django 3.1.7 on 2021-11-28 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0139_auto_20211127_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='names',
            new_name='name',
        ),
    ]
