# Generated by Django 3.1.7 on 2021-11-28 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0141_buy_detbuy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='name',
            new_name='names',
        ),
    ]
