# Generated by Django 3.1.7 on 2021-11-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0147_auto_20211128_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre',
            new_name='name',
        ),
    ]
