# Generated by Django 3.1.7 on 2021-11-29 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0148_auto_20211128_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='name',
            new_name='names',
        ),
    ]
