# Generated by Django 3.1.7 on 2021-12-15 15:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0150_auto_20211130_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha Compra'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='prove',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='detbuy',
            name='buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.buy', verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='detbuy',
            name='cant',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detbuy',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=9, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='detbuy',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='Repuesto(s)'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='cant',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=9, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product', verbose_name='Repuesto(s)'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.sale', verbose_name='Venta'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha Venta'),
        ),
    ]
