# Generated by Django 3.1.7 on 2021-08-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210802_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dniuser',
        ),
    ]
